/**
 * Generate services/gateway/src/generated/embedded.ts — bakes the built HUD
 * (apps/hud/dist) and the skill manifests (skills/) into the binary so the
 * compiled single file is self-contained. Run before `bun build --compile`.
 */
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(import.meta.url), "..", "..");
const distDir = join(root, "apps", "hud", "dist");
const skillsDir = join(root, "skills");
const outFile = join(root, "services", "gateway", "src", "generated", "embedded.ts");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".map": "application/json; charset=utf-8",
};

function walk(dir, base = dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p, base));
    else out.push(p);
  }
  return out;
}

const hud = {};
if (existsSync(distDir)) {
  for (const file of walk(distDir)) {
    const url = "/" + relative(distDir, file).split("\\").join("/");
    hud[url] = { type: MIME[extname(file)] ?? "application/octet-stream", b64: readFileSync(file).toString("base64") };
  }
} else {
  console.warn(`[embed] no HUD dist at ${distDir} — run "npm run build -w @aos/hud" first`);
}

const manifests = [];
if (existsSync(skillsDir)) {
  for (const e of readdirSync(skillsDir)) {
    const mp = join(skillsDir, e, "skill.manifest.json");
    if (existsSync(mp) && statSync(mp).isFile()) manifests.push(JSON.parse(readFileSync(mp, "utf8")));
  }
}

const banner = "// AUTO-GENERATED by scripts/embed.mjs — do not edit. Regenerated each packaged build.\n";
const body =
  banner +
  `export const HUD_ASSETS: Record<string, { type: string; b64: string }> = ${JSON.stringify(hud)};\n` +
  `export const SKILL_MANIFESTS: unknown[] = ${JSON.stringify(manifests)};\n`;
writeFileSync(outFile, body, "utf8");
console.log(`[embed] wrote ${outFile}: ${Object.keys(hud).length} HUD assets, ${manifests.length} manifests`);
